[package]
name = "telos-reth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
reth.workspace = true
reth-node-builder.workspace = true
reth-cli-util.workspace = true
reth-chainspec.workspace = true
reth-provider.workspace = true
reth-node-telos.workspace = true
reth-telos-rpc.workspace = true


clap = { workspace = true, features = ["derive", "env"] }
tracing.workspace = true

[lints]
workspace = true

[features]
default = ["telos", "jemalloc"]

jemalloc = ["reth-cli-util/jemalloc"]
jemalloc-prof = ["reth-cli-util/jemalloc-prof"]
tracy-allocator = ["reth-cli-util/tracy-allocator"]

telos = [
    "reth-node-telos/telos",
    "reth-chainspec/telos",
    "reth-node-builder/telos",
    "reth-provider/telos",
]

min-error-logs = ["tracing/release_max_level_error"]
min-warn-logs = ["tracing/release_max_level_warn"]
min-info-logs = ["tracing/release_max_level_info"]
min-debug-logs = ["tracing/release_max_level_debug"]
min-trace-logs = ["tracing/release_max_level_trace"]

[[bin]]
name = "telos-reth"
path = "src/main.rs"
required-features = ["telos"]
